-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 22:47:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blog_pessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Blog_pessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog_pessoal` DEFAULT CHARACTER SET utf8 ;
USE `Blog_pessoal` ;

-- -----------------------------------------------------
-- Table `Blog_pessoal`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog_pessoal`.`tb_temas` (
  `id BIGINT` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `tb_postagens_id BIGINT` INT NOT NULL,
  PRIMARY KEY (`id BIGINT`));


-- -----------------------------------------------------
-- Table `Blog_pessoal`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog_pessoal`.`tb_usuarios` (
  `id BIGINT` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id BIGINT`));


-- -----------------------------------------------------
-- Table `Blog_pessoal`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog_pessoal`.`tb_postagens` (
  `id BIGINT` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `data` DATETIME NULL,
  `tb_usuarios_id` BIGINT NOT NULL,
  `tb_temas_id` BIGINT NOT NULL,
  `tb_usuarios_id BIGINT` INT NOT NULL,
  `tb_temas_id BIGINT` INT NOT NULL,
  PRIMARY KEY (`id BIGINT`),
  INDEX `fk_tb_postagens_tb_usuarios1_idx` (`tb_usuarios_id BIGINT` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_temas1_idx` (`tb_temas_id BIGINT` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id BIGINT`)
    REFERENCES `Blog_pessoal`.`tb_usuarios` (`id BIGINT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_temas1`
    FOREIGN KEY (`tb_temas_id BIGINT`)
    REFERENCES `Blog_pessoal`.`tb_temas` (`id BIGINT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
